language: node_js
node_js:
  - '0.11'
  - '0.10'
before_install:
  - npm install -g gulp
  - npm link gulp
script:
  - gulp build

after_success:
  - gulp deploy --apikey=$GITAPIKEY --build=$TRAVIS_BUILD_NUMBER
    
env:
  global:
    - secure: HcIPE9k6xYRe1e064LXdlyQyBWSbI3xYd+xApDACp+dgHQmQvJXstBAtrdjETniDwMFGTopbr40/+ZNsSKvSFQS3lTzCj9kDa07DGNEzIfidd3xHTgqKZNWSgqyS/jZrNlEnR8QhA1ggdLhE91WTFbpbitcxYHOHLrchFawIzOySUtiM9dkiCK7Z57PMjUwP9lSqQUqrIX0KajsfSWBCQNsxvYgqv1eD97R7xtOq9WcDAuFBHj5+igXhYTAnC/oyDjCcMJNeYu3veQRR6uNVxgVCeJP76lvAO5sQAqZ4t/ONJnWBgf2DAz6nW4XTF3m0wI9WsfTEYh5bxOFBxhhhsjcsx7Rv0EHaMfDCUPPYctFV4N9VWg50D2APfyFmXhy+ZOoln0PzQYJTIjySIXQma4QGkZqT7Wrn2IBDIBJpV3d5nupUL8+/ejHAfYxF1UIl5Awoln1Hq0Pc84OQPrLmhM3PGD2ag4M5FeNIOuqQ6JjaIVnkBSr2uq8X1Bgr09q+kw410CiLehcScx360Z48e2XBm1Yo6Ho56N4PBWJSOA026Tn5qt3czLnRK2TjyuiFwfiQsczGKOaphZSltYL6nm0+ej/8PUPp2r2wZJ3alt6KccpE1SJXoChpMs/kg4nTOOG8ACL9ejMVWqcd1rveJIoUvQqjSRdGyGRdHoC9YMQ=
    - secure: OGNlvotZ8JN1tYhWN7Jb49zmqc4188k7EAyBhKATLzazlG41VuM4WZ1h+MU6EHSBJ4ZLBtrwic145Fe+o06RuHXEx/ZSWBVXjRhsjmuBfDDcLSBBUXjfauakl2P6HBaA8qr7RebVefUW0DfRpXdBS5CAYMvJk2TQ8JIVhcRSLup6OWvigGY0ZdaXzgXX2RjA96DbvI0NEvstrioO640zT9dNZJjzzudvc8NYzTNDQ6KqLNUlQV18V9VeXL4oRYl+c844mctWsKq/any1xabtIu69lExhCDvwZk2xyLl/KzIvV0hixXun5oNTgGnCsVNnls4nARtUHW32l2z18UThQVI54lnYFqHEc2Nf9JYd/QaeaBKqqEoFdTSaVctPjoirUW/l2cQ029YF44ekgMWHdK+ZaPV34MvEk12oQEI6AeFA2MISITWv34+F5ODFidacfANMyqZKPrNr5rzBsjY+80nWC+0+wTnhIXJVOAT1UidjILykziUGjA/VgbUl86d9XjDhUtpN87K1lDn+WYoqYqZmR9E2dxa6eXWSCVfL8SS8yBfYcGUHU2YvFQdVxWMuR2ow70Yo65fuCDt2MrhXou2u6qCZY0iFLWxLcHlY2jH7Pv8nOEhlMF78foIgTFc9lIgOn0H2dp0cGprImxWEtbGE7ysoG3X5YpGJRnRZvMQ=
    - secure: RXXf0y60TrFWV7UGFHaA2tmQhbTsRrmoTJOdwyE8QElLaQMaZGRtMb0+GwESP5EsunpddO+HPoqEjUGLiwW/a+M2E4R97tIywX7t/YoiDwurUusmeiScQzA2LOHU9CiigJtvR1DXJP7op00yrbhih30iACkKvIqsnsEWzERez9KmiobwmLCyyhJUsRWV+vJyNHVJ9/qPcuzqvFUW6q45x+ZQwJbuwE17ogkBEKj2lcuWO+yHBf4AyFKrrVtMLxLsYnlYG4zyUtbzCpkpt84Lhg4cFy1UAc3g7yZw/hP0eRwTz/KUL4Ye5tJ0tj///HqNhuhMhMoM54kCPUJE8uKHIItSkZiEviqJXWQ8P63jYFKK61ZbvRNah5ZIuL4sqsHeeEnKhcbqTagU+k+cH/Z/tr+d30qVmHhQD4yEecg8akq7rPZJM+DKuRzUPx6taNm12X5OC4K5qg0I4I4kqW7x9Jctgqd0HyPEetJvFWy4l6bK/4ewPSOkp4ljDXA952LNLPUXCJTlWqo3pgW/KAbZPWMgMcz86Z2HqrEGebsjCWJWMLNWmbKvrXllazA+EFmHZxOFHyGuEoitK9zLtXVrwKOxIo8ymzuIapDO4SXifVvVkk1OEXkm3+ytSu6cWHg/cPqlrWROvNFMvmbfciaTVkJ5MYbkuFiKgwI7FyFHFpw=


addons:
  sauce_connect: false
