language: node_js
node_js:
    - '0.11'
    - '0.10'
before_install:
    - npm install -g gulp
    - npm link gulp
script:
    - gulp build
deploy:
  provider: releases
  api_key:
    secure: G39HvGk+G6pEtzlqmONl1FJYbclySOk8WuUYmM+l9HKK+8yqgOfD2ugvspYiwraCF6qsXU56D/vkaudVfX0ZWjI7bLMLIS7CgEuDv9GUVaKopbDXueOhx3rbH/f4N9J/1xeEmvrRh00WVYPy8Is61VEhWijYm5HClQOuodi7JTnjGgQXzoAECkER+lgToT8c8acVvOgyuMEuhCTaOFvjWx3coybD6tu2Ox5vrnbcbApeu7C0qQHLrZuBMNvYIFV/qbKmEopLb116+A517MQocu5UOkxdSee8fFRcFybWLw0TwOKtgWban7fZu5nRb7qXVwrfsDSUuE7AXtaNv8f9QDm9o3HHNPAKgPx7BDJU3shQ0V9WoN+jjQ4lSkPgt4ZaysnzSlNQEDNAfndVc2oILyTaaTnB2kbQz6ubS3Jk+Qx47PTr9FQQlUOrB1bKotgyiA1hmTRaQnkVgFle/rtceZL93lBu9ztkUexHvKptOxnptPM4qOOwVc7OLLKzwFdyzq2mI1wa4Q5NXRPYL8gvq1A6l5msJjOZDZ70bVRdNwUtC+uX+rmmT8QgpK9zRBmGOtbu/7Yh0xH292YTyGFF1XwjlYf385MvfsZX5Pd039ldF4wJTMD0yhpeDkdZDvQg7LZG035/gN61m8qozO5rGtyTc+FDuMVHQg+eToG5EWw=
  file: dist/*
