language: node_js
node_js:
  - '0.11'
  - '0.10'
before_install:
  - npm install -g gulp@3.9.1
  - npm link gulp@3.9.1
script:
  - gulp build
after_success:
  - gulp deploy --apikey=$GITAPIKEY --build=$TRAVIS_BUILD_NUMBER
env:
  global:
    -
      secure: AZtZtBogFN06TqU8OKA0ITEb5LHZ66b9QesGlUQO6vUH79QQ5cr+5QvzkHViOVjNY7TsB1lFF/hU7ZWBr66Q+NCV+u5Yf6qxoQ21MCEHCmG39UKVFPMdyIcWDgh4moeq1XUWyveCrDPP0ph6MkhMveiph7y8mMbt6osa+C0jEN7EZY92Cuqvj4ogb9LFl6aCxOwuA5FDKaXPtJpU8JsJAWbnNJBK7ZeE7LFchngn19gQfkl8cAx7DLEqZeYLTHLweU1P5kyy61hgboQxHATFWZNTfQYcdty/LLe+nLperQKlhcEegpH7T+CHDyWixU+V79ieLYjjc7a/mMqlaT9ehCZB6TN6DxfTKrKw79pytiiSOF2Row9hPZule3P7OcC2X6J7x9Ej/eitArlTB3sGOk7SmvCl/nCdednHWhmpSkn6LrgvjgwiPxGIThdaYbd7Ge4Q2b7Fa9V9D9/ep5CDMa9XK5U4Rk1WRuPTqM+4KWToT6Dm95hb8ahQD7nGzhcEMkCSIUCFlv78YebVtQzftmybDaSx+58tMLuMiXBXCIFhBbOSBXxMSx+EJY4CYQwR/P/vpnf6t4gJb2hWujUHua2ZRO3khTI4yCBR2nKRGii5gCeMhdRcDnczRq+vrmHkEBbvQMZoNKZkeUSqlEnc0pPnD7uVYCb6Hb+7bQ1qGMM=
    -
      secure: edP8HhgOo3I5cTX9Kb5SXIO7dGOCgjWyrOlJ5oEGSGL7Lgor2+sEF2wYxEO5bXElmE4h9TdsTBhw7qbF/94/EvdmwbZg48l/7naDL2lyWFVfmiNyrlQcIxja9MJYyjTPDb1kuJDMZaoSXaRQRkO7supNLS2YCwfvCQQjyFaVpFKTbm3LMcwqti5PJpx1YDtCBbUyb8X96inSEzqq1ZXAGAnWAnpW6Vqpl4X4TYRfDz/xH3MdUB8+bhIamquHj0F4vgufY7QNpYQ9m5ldB0fVzhEwKXIgNTGD47+V+zlBd7KH8dG95RzyaSE59eOWTKfuma/MHQJihVNrh3gpjpki4U/0nWXaOunlTGiL/2sn8731mk+Zu3biIxgnq8esINfQFHrmZ5N6mzl8VpeTBIUOvk075p5MYsZc9MW4BdqqTAmqg/EbMDvW8noN+5etX+gY4Ve/ERUPc7faMdFNNagV8G9M66Z1sGH2m7LuN6ZqxsTyP18U0izAUKDItijFDoa7oQKOB7gqKL06D6AzsSe1UbiM3fqbjwjwgmG7ZP7hVazMrER4CONVMqTmQKvozKgq/FIarhh36qRPTxARqs/Bqd9w29RzrylCz/c+JirRb04isNPB88Uu2I3MP9hazIZo2Qi0Ck8KJjqzwIDX/dhRlmhNTwzRwu/WCW7vAsmqMOk=
    -
      secure: Kg/4zTX/zVpV10HdXtocN7PerL8GtGyWoRqWfi2UYDn2+Ync6sKPEy9ckHfkk2H+Hf26jYla2nLti9EskarkDmorBmyfpX2C01BKM8eT4I+JWxXT27QhvWA7FVnhKy1EnyOVsStc+puM5aPYTDaPpleZGVzFCEqFJwKcDvtRUP7naSJjsnP1mXylkZW4FefntZkQf4O/z9iYnhRE17kEM2OPl1Xm0hFE3Hd3m0FnlXIyec2x5gyq5v5NO9dwhA2KlVfcmF0bdJ1d+SebK1h2iSMvO7E7S7U19AAtXlxUTrOuUKnFCqiHzT7uthZOn5cWDQjqAQjQ5/WWDsqC3KH6SltUG6EzcCoXLC0C5YJffWp7Gtg429edZo2c018VOve2rh4ySNGsoEZDMtwjyFultkkNOWQu2b0rpEwQ+iWkkeaFdFXTdi6nxGqujW3kRg6WHP+pPV1rCAcTjJ26bscb4ijp2oLpr9yq8qxGRrl3GyT1Jy7gVIdxHZMttaiEcvxjyfH+E2jnxPfl3c/bEfL6yHCmhjB8z5pJwVJw2DQ4/Rc4IMsafGeNkqmYiJGCQpe6edrGpAq8XsLyVFc0X9BpOgcnZtzsgw0OZXSMPWHhjmGjwPTuEcdBOf41M/srStFz98WHOAZi0vFhSlIWeZ4OGg792tDtGJq9mCIkJ7gA/qM=
addons:
  sauce_connect: false
