language: node_js
node_js:
  - '0.11'
  - '0.10'
before_install:
  - npm install -g gulp@3.9.1
  - npm link gulp
script:
  - gulp build
after_success:
  - gulp deploy --apikey=$GITAPIKEY --build=$TRAVIS_BUILD_NUMBER
addons:
  sauce_connect: false
