language: node_js
node_js:
  - '0.11'
  - '0.10'
before_install:
  - npm install -g gulp
  - npm link gulp
script:
  - gulp build

after_success:
  - gulp deploy --apikey=$GITAPIKEY --build=$TRAVIS_BUILD_NUMBER
    
env:
  global:
    - secure: m7k0qN4PCIFTRsppIhSA39hrN0/CTuCZrA1AaOZG/ldJhRjLuLDIJsEFYtphje2OzNap9ljB01lD0PvYVIRikKKz0YO1gI0Fnfsj3RM1H0BoPcVXkBfvk/jbNW+3sCJSAxbE23TA6DLwJtredFc09vlIl6SVOgsbljZpwPPSFRoF28RIYUI8Q4+o3QfooDYEQgSioJQbC/1KH05lLZLFA0aivzRJw8BDXxyMvHVvmFu3zynG9srouyoVoHUcQR5toq9oP3jAV1aHrEQRQkCCvQRXP6eFQ8skJFY0/Su+BpzgBSAXEDCHsCunstnVhG8EbnCll66D1CBWcp8QM4COMTGzo0xoPEyW9mp/8hVuMllpdrFRB9Iif/sVbu3PWYZxNKsoUcUl63IxgpGLtzJo5pakYlUbZuhcyjMREsEgHueayNOnss9fd4sJ/84oc2zvYnDyRq4ytnh+zZqPy4fd8Qy6oiVO5VJ1OjCVE73VNZ5JSA8XT7ASTn/U52CmJNKA6aI3oXVOLeYjOXO2HCT90G+PFScF09C2MkIwdWSOqcy+UFwKFaSp08IhxMY44l4vAtMg/xuoU76TMs/XVaGLSpBM0nR1uK1KTfzWccDeChZzIoL55zVVUGX3XaeruYabSyY3DZD71l80lzbUkg5MUzpCF9J6Nz4MacXtky/9MuU=
    - secure: S+39v0cUtWSf5JmO0dL5w2CSKSOZZS2OxcLbKzqbB4om/fpP5KtNrGnwMFmm626wES1HDeapVVW6zD9kxLUFBe+XwwnWSW3DY/MuXxb+yL8mQZRCQ6DpWaBOq0xWnk1iEw7oQ9x1tUBHDkRPKuc7A3Y3Kfq++9zj1+6eSo2z9jVhhJxnzf+N6ryqEGfN4o4G5Il8KdOQMyIj8Z+bz6SZbj8UGoDz5Nz/CYXmzDePcn3k1tF85RVb7CwT1mMtsiZrInQJ8qbWzoKAoaNqr17QPzI3vOW0hvdD1hRcrhceUMcOVBbIFLURHiKD7dm30QsANgNwryqmYmCaVd1lymbkBmMdpw+5cJ8T7d44qFrQh8HBaoMbTIn31vMdWGw2l6tVh2coZIKCVfN7NC7K4kWIp7Z6gYTY0F23GsdETMdDzUol8xli+bgBWG7ZnjXuWldXHvcjNARSrBE/MLYZK32qI4t5xMQJFosIs8MfvnUvs5WpHOgNxOO/hSzJQQM2AxdTPMJCNKEWOJVSBfstX8p5A6bkuw2tStYNY60a+izrkWrVcWimK50dasHNXr5ok2ET4fC7YyzVvJdv5Ql/Yq1+EoqKSWh7TZz9UzpVeAzAFnS1bZId8ixP8TMb15hGJ8zfHyhjCozr5F6pglDYxpllx6gDkWeYr84OuGbXwEjzItA=
    - secure: MyzpTHzV0OtcUtL/RkNKls9Nk+SGcapq3o5+5xNtwkcu+sM7jm9XOg5pmxUYuNlfqE7pvbnDiNFh/ka0UMI96OnSARjuv3LxRDFKmXtd48utjvxiLt31kPPcSM7cIn5lX423yuZUxlJX7BP4dWr4fs5b1zTweSkUSl0CtFk0O+BzH9JPT02bldqXT/byZiruKyDU94hQ7Cwp3ePwd3HyyLPb8Loqi6BKKbLmqKlcFfFTaQPG9EuAtUjL6yRVt46NokH/UfZWr9xDML/x4S4WwhYBVIoxKYl7Ur7UVNJUOTD5cGodQnl7FILOhJuGp+jgwZk2Z2evP7XlYY2KQfPYucnw8dxTNMYiAeT/6IVLAxtbMJ3dSkY+KzD/iReGSUTnxHD06j0cuwEfa9WBZCV8ylW4X/SW2ouP5I1+Sbk2n5QhJH+j9fN8YZ1E27hGrazvdw6rX43xuZhTUWuC0FrS9h5x83bg9QSWkGSjRWnueOEldLL6e6jv/prlqcSLyUBIDEIdnWUdn9bTzihwxuC+1Ba4Mf1iQrWyd9oZElRAXkJvyWJPaVy9YTnLCImNSyAyuZDchA5rMc3n9soafDio1Ws18w0gVVvXgbOhqhu8bj4Zvyh3eUqwELsUyCi9trAVpmGOHxfmtAJgRR/+sr+Xe6i7neAS9hssr5UGguVpcTs=

addons:
  sauce_connect: false
